### Spring properties
# Service registers under this name
spring:
  application:
    name: CustomerService

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:7171/rest

# HTTP Server (Tomcat) Port
server: 
  port: 7171

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false